/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import reactor.core.publisher.Flux;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {


   private static final Logger log = LoggerFactory.getLogger(App.class);



    public void fluxDemo_01() {
      Flux.just("A","B","C")
        .subscribe(
            data -> log.info("onNext: {}", data),
            err ->{ /* ignored */ },
            ()-> log.info("onComplete")
        );

    }

    public static void main(String[] args) {
       App myApp =  new App();
       myApp.fluxDemo_01(); 

    }
}
